In [1]:
import numpy as np

import gymnasium as gym
from gymnasium.spaces import MultiDiscrete

In [24]:
d = MultiDiscrete([3 for i in range(5)])
x = d.sample()
x

array([2, 0, 0, 1, 2])

In [30]:
u, c = np.unique(x,return_counts=True)
u

array([0, 1, 2])

In [31]:
c

array([2, 1, 2])

In [28]:
for i, j in zip(u, c):
    print(i, j)

0 2
1 1
2 2


In [34]:
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

In [1]:
from abc import ABC, abstractmethod

class MyBaseClass(ABC):
    def __init__(self, base_attribute):
        self.base_attribute = base_attribute
        self.common_attribute = "I am a common attribute"

    @abstractmethod
    def my_abstract_method(self):
        pass

class MyDerivedClass(MyBaseClass):
    def my_abstract_method(self):
        print(f"Method implemented in the derived class. Base attribute: {self.base_attribute}")

# Example usage
my_object = MyDerivedClass(base_attribute="I am a base attribute")
my_object.my_abstract_method()

# Accessing the base class attributes
print(my_object.base_attribute)
print(my_object.common_attribute)


Method implemented in the derived class. Base attribute: I am a base attribute
I am a base attribute
I am a common attribute


In [3]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
mylist = [-1, -2, -3, -4, -5, -6, -7, -8, -9]

# Define a condition
condition = arr > 5

# Use numpy.where to get indices where the condition is true
indices = np.where(condition)[0]

# Print the result
print("Indices where the condition is true:", mylist[indices])


Indices where the condition is true: [5 6 7 8]
